include module for PermissionTemplate
When using the postgres adapter, the following error happens when creating collection permissions.

```
NameError: uninitialized constant PermissionTemplate
/Users/elr37/Documents/__DEVELOPMENT__/Samvera/TEST/nurax-pg/vendor/bundle/ruby/2.7.0/bundler/gems/hyrax-8c6b1d32e8a1/app/services/hyrax/collections/permissions_create_service.rb:17:in `create_default'
```

This happened because the permission template was referenced without the module…
```
PermissionTemplate.create!
```

The fix is to reference permission template with the module…
```
Hyrax::PermissionTemplate.create!
```