Role mapper should fetch keys
This raises an error when the environment isn't found instead of a Nil
pointer error like:

```
NoMethodError (undefined method `each_with_object' for nil:NilClass):
  hydra-access-controls (9.2.2) lib/hydra/role_mapper_behavior.rb:35:in
  `byname'
    hydra-access-controls (9.2.2) lib/hydra/role_mapper_behavior.rb:20:in `roles'
    hydra-access-controls (9.2.2) lib/hydra/user.rb:18:in `groups'
```