Require rails/generators explicitly
This resolves an issue where Rails::Generators::Base is not autoloaded leading to an error: NoMethodError:  undefined method `subclasses' for Rails::Generators:Module
The require for rails/generators/actions isn't needed because rails/generators autoloads it.