Adds production block to generated redis config.
Our other config files (see: fedora, solr, database) include blocks for development, test, and production.  So too should the redis config that Sufia generates, else you get possibly misleading error messages, like:
```
RAILS_ENV=production bundle exec rake db:migrate
rake aborted!
NoMethodError: undefined method <top (required)>'
```