Fix typo for the raise statement
This commit fixes a typo in the raise statement. In Bulkrax, the error
seen was "NoMethodError - undefined method `/' for "Failed to aquire a
lock from Redlock due to a Redis connection ":String"