chart: include postgres containerPorts default in values.yaml
due to the nested variables, having the parent `containerPorts` value unset can
cause errors:
```
Error: UPGRADE FAILED: template: hyrax/templates/configmap-env.yaml:17:21: executing "hyrax/templates/configmap-env.yaml" at <.Values.postgresql.containerPorts.postgresql>: nil pointer evaluating interface {}.postgresql
```