Removeing solr_config which is out of date.
It doesn't have a _version_ field which is causing errors:

     RSolr::Error::Http:

            RSolr::Error::Http - 500 Internal Server Error

                   Error:     {msg=SolrCore 'test' is not available due
                   to init failure: Unable to use updateLog: _version_
                   field must exist in schema, using indexed="true" or
                   docValues="true", stored="true" and
                   multiValued="false" (_version_ does not
                   exist),trace=org.apache.solr.common.SolrException:
                   SolrCore 'test' is not available due to init failure:
                   Unable to use updateLog: _version_ field must exist
                   in schema, using indexed="true" or docValues="true",
                   stored="true" and multiValued="false" (_version_ does
                   not exist)

                            at
                            org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:745)

                                    at
                                    org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)

                                            at
                                            org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)

                                                    at
                                                    org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)

                                                            at
                                                            org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)

                                                                    at
                                                                    org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)

                                                                            at
                                                                            org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)

                                                                                    at
                                                                                    org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)

                                                                                            at
                                                                                            org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)

                                                                                                    at
                                                                                                    org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)

                                                                                                                  URI:
                                                                                                                  http://127.0.0.1:8983/solr/test/update?wt=ruby&softCommit=true

                                                                                                                         Request
                                                                                                                         Headers:
                                                                                                                         {"Content-Type"=>"text/xml"}

                                                                                                                                Request
                                                                                                                                Data:
                                                                                                                                "<?xml
                                                                                                                                version=\"1.0\"
                                                                                                                                encoding=\"UTF-8\"?><delete><query>*:*</query></delete>"